{% set name = "pyobjc-core" %}
{% set version = "7.3" %}
{% set sha256 = "5081aedf8bb40aac1a8ad95adac9e44e148a882686ded614adf46bb67fd67574" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - fix_for_conda_build.diff

build:
  number: 2
  skip: true  # [not osx or py2k or python_impl == 'pypy' or (arm64 and py < 39)]

requirements:
  build:
    - {{ compiler('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    # - libffi  # TODO: switch to CF's libffi
  run:
    - python
    - setuptools
    # - libffi  # TODO: switch to CF's libffi

test:
  imports:
    - PyObjCTools
    - objc

about:
  home: https://github.com/ronaldoussoren/pyobjc
  license: MIT
  summary: Python<->ObjC Interoperability Module
  license_family: MIT
  license_file: License.txt
  doc_url: https://pyobjc.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - kastman
    - leofang
