{% set name = "pyobjc-core" %}
{% set version = "8.0" %}
{% set sha256 = "4cd0735cdb7a7b959def0fe1769df74e0ab6de5ea1ca40f1464d2ac78b85326f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - fix_for_conda_build.diff

build:
  number: 0
  skip: true  # [not osx or py2k or python_impl == 'pypy' or (arm64 and py < 39)]

requirements:
  build:
    - {{ compiler('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - libffi
  run:
    - python
    - setuptools
    - libffi

test:
  imports:
    - PyObjCTools
    - objc

about:
  home: https://github.com/ronaldoussoren/pyobjc
  license: MIT
  summary: Python<->ObjC Interoperability Module
  license_family: MIT
  license_file: License.txt
  doc_url: https://pyobjc.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - kastman
    - leofang
