{% set name = "pyobjc-core" %}
{% set version = "6.2.2" %}
{% set sha256 = "38e7b15a042439dadd18b28b78229e52fb882460fc16ddbae342b9972d5a827c" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [not osx or py2k]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools

test:
  imports:
    - PyObjCTools
    - objc

about:
  home: http://pyobjc.sourceforge.net/
  license: MIT
  summary: Python<->ObjC Interoperability Module
  license_family: MIT
  license_file: License.txt

extra:
  recipe-maintainers:
    - kastman
