{% set name = "pyobjc-core" %}
{% set version = "5.1" %}
{% set sha256 = "d29fc9f6dbc5b81042350fcc8acf24ef0174841f8a24faf8bad985522e22ab9e" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  skip: true  # [not osx]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools

test:
  imports:
    - PyObjCTools
    - objc

about:
  home: http://pyobjc.sourceforge.net/
  license: MIT
  summary: 'Python<->ObjC Interoperability Module'
  license_family: MIT
  license_file: License.txt

extra:
  recipe-maintainers:
    - kastman
