{% set name = "pyobjc-core" %}
{% set version = "7.0.1" %}
{% set sha256 = "7213bfd48c49f5b4d479256924e0120d728ed449de8188cba9e204c434ed07f2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [not osx or py2k]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
   - {{ compiler("c") }}
  host:
    - python
    - pip
  run:
    - python
    - setuptools

test:
  imports:
    - PyObjCTools
    - objc

about:
  home: http://pyobjc.sourceforge.net/
  license: MIT
  summary: Python<->ObjC Interoperability Module
  license_family: MIT
  license_file: License.txt

extra:
  recipe-maintainers:
    - kastman
