travis:
  secure:
    BINSTAR_TOKEN: U9xKovMgdYPKfTFrH5ZU955G16bVQM4r4wNLA+VmWPHN5hTGGI8oOVblPLDwojf3ipmvU2DLGniaIDvkicSQ9prmB9Bm1lwtqpRRxpLMU5Px/dcBQmcflgdva1L6A/U3EhXw+vyAXOT8195YseBDyHuSke7bpkqCE2UN4o/5K7W02aWYYOItR6qs94WozgYPq8QmXHXQE98Hff+4uGztkkSB0viwDMe1/SnL3BR3Sq82vbux6kd6cYH17s0CgfuD8scE8w2a3oJRXkAYUEbw69hZqArdxNoyhhgcWoSytvajbG6/NKBL0m425fojvg/AQS0rJU+3UVCFYc5pdcLIEseO28CbXd3KMijysYbljgndTTd/mJi/JLT5bkilVQNKqUPp7kTxnbHJjxGwHKiLFdTMmJWgHpolgEKLIrQcv2Dsye12whaBN8zfyBSXqb0/4QQGIW/Yj/0TphlhorukPpNnqnjXNdbJaPGaN/qbL8b5EeV2cQtQgZHONMDVCVx3rta7JCjry0XcT6CY/iuRTHUfJxS91aWNsvYvRohC937WCIYZriF68jxMQG0c2f3Ib+cmD65sEGWbPDnYqKI9dB8CuqOlCeQ7WxZgMIXNycAGf8BFAgkq7S2gqIvL0azdZ2A03ijuMxL2tXEJ4J4QGhagsFXIaPBqpzGLnCa1m8s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
